config/routes.rb
Paydici::Application.routes.draw do
  match "updates/public_index", :as => :updates_public_index
  resources :updates

  get "home/index"

  devise_for :users

  
  root :to => 'home#index'

end

app/models/update.rb
class Update < ActiveRecord::Base
  validates_presence_of :brief_message
  validates_presence_of :details
  
  after_save :update_users
  
  def self.latest
    Update.order("updated_at DESC").first
  end
  
  def update_users
    return unless self == Update.latest
    # TODO: do the following in a single SQL statement
    User.all.each do |user|
      user.update_attribute(:new_to_update, true)
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :new_to_update
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user!

  def index
    @first_time = current_user.new_to_update?
    current_user.update_attribute(:new_to_update, false) if @first_time
    respond_to do |format|
      format.html # index.html.erb
    end
  end
end

app/controllers/updates_controller.rb
class UpdatesController < ApplicationController
  http_basic_authenticate_with :name => "admin", :password => "admin", :except => [:public_index]
  
  # GET /updates/public_index
  def public_index
    @updates = Update.order("updated_at DESC")
    
    respond_to do |format|
      format.html # public_index.html.erb
    end
  end
  
  # GET /updates
  # GET /updates.json
  def index
    @updates = Update.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @updates }
    end
  end

  # GET /updates/1
  # GET /updates/1.json
  def show
    @update = Update.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @update }
    end
  end

  # GET /updates/new
  # GET /updates/new.json
  def new
    @update = Update.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @update }
    end
  end

  # GET /updates/1/edit
  def edit
    @update = Update.find(params[:id])
  end

  # POST /updates
  # POST /updates.json
  def create
    @update = Update.new(params[:update])

    respond_to do |format|
      if @update.save
        format.html { redirect_to @update, notice: 'Update was successfully created.' }
        format.json { render json: @update, status: :created, location: @update }
      else
        format.html { render action: "new" }
        format.json { render json: @update.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /updates/1
  # PUT /updates/1.json
  def update
    @update = Update.find(params[:id])

    respond_to do |format|
      if @update.update_attributes(params[:update])
        format.html { redirect_to @update, notice: 'Update was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @update.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /updates/1
  # DELETE /updates/1.json
  def destroy
    @update = Update.find(params[:id])
    @update.destroy

    respond_to do |format|
      format.html { redirect_to updates_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/updates_helper.rb
module UpdatesHelper
end

app/views/home/index.html.erb
<% if @first_time %>
	<div class="update">
		<p>This is your first time logging in after a feature update: <%= Update.latest.brief_message %> </p>
		<p>Click <%= link_to "here", updates_public_index_url %> for details</p>
	</div>
<% else %>
	<div class="update">
		This is not your first time logging in after a feature update.
	</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Paydici</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= link_to "Sign Out", destroy_user_session_url, :method => :delete %>
<p id="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/updates/_form.html.erb
<%= form_for(@update) do |f| %>
  <% if @update.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@update.errors.count, "error") %> prohibited this update from being saved:</h2>

      <ul>
      <% @update.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :brief_message %><br />
    <%= f.text_field :brief_message %>
  </div>
  <div class="field">
    <%= f.label :details %><br />
    <%= f.text_area :details %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/updates/edit.html.erb
<h1>Editing update</h1>

<%= render 'form' %>

<%= link_to 'Show', @update %> |
<%= link_to 'Back', updates_path %>

app/views/updates/index.html.erb
<h1>Listing updates</h1>

<table>
  <tr>
    <th>Brief message</th>
    <th>Details</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @updates.each do |update| %>
  <tr>
    <td><%= update.brief_message %></td>
    <td><%= update.details %></td>
    <td><%= link_to 'Show', update %></td>
    <td><%= link_to 'Edit', edit_update_path(update) %></td>
    <td><%= link_to 'Destroy', update, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Update', new_update_path %>

app/views/updates/new.html.erb
<h1>New update</h1>

<%= render 'form' %>

<%= link_to 'Back', updates_path %>

app/views/updates/public_index.html.erb
<h1>Recent updates</h1>

<% @updates.each do |update| %>
<em>Posted at <em><%= update.created_at %></em></em>
<h3><%= update.brief_message %></h3>
<p><%= update.details %></p>
<% end %>

app/views/updates/show.html.erb
<p>
  <b>Brief message:</b>
  <%= @update.brief_message %>
</p>

<p>
  <b>Details:</b>
  <%= @update.details %>
</p>


<%= link_to 'Edit', edit_update_path(@update) %> |
<%= link_to 'Back', updates_path %>